### ISSUE TITLE
publish .vsix with each release tag

### ISSUE THREAD

**Issue by gsmachado** [neo-project/neo-blockchain-toolkit#10]
It would make developers' life way easier to automate the packaging of the Neo Blockchain Toolkit if the .vsix file could be attached to GitHub releases tags.

Like, for example, as the vscode-java (from RedHat) does: https://github.com/redhat-developer/vscode-java/releases/tag/v0.61.0

I understand that you might want to concentrate all the downloads and user flow at the marketplace, but, due to some packaging reasons, it would be awesome to have the .vsix file in each release tag, here in GitHub.

👍  😄

**Comment by gsmachado** [comment]
Any news on this? @devhawk @djnicholson

**Comment by devhawk** [comment]
We are going to do this going forward, but there hasn't been a release of BCTK since you opened this issue (we're in a bit of a release lull as we work on Neo 3). 

We did follow this guidance and did a [github release](https://github.com/ngdseattle/visual-token-designer/releases/tag/v1.0.3) to match releasing [Visual Token Designer v1.0.3](https://marketplace.visualstudio.com/items?itemName=ngd-seattle.visual-token-designer) on the marketplace

**Comment by devhawk** [comment]
As of Neo 3 RC1 release of BCTK, we are using a GitHub workflow to produce a release which we then upload to nuget/vscode marketplace. example: https://github.com/neo-project/neo-debugger/blob/master/.github/workflows/release.yml
